import { DepartmentEntityProps } from "../../../constants";
import { getDepartmentHierarchy } from "../utils";

const departments: DepartmentEntityProps[] = [
  {
    id: "1",
    departmentHierarchy: "",
    departmentName: "first",
    _links: {},
    administratorId: "12312",
    creationDate: "12312",
    historyId: "12312",
    isActive: true,
    isDeleted: false,
    isOwner: { UPDATE: false, DELETE: false },
    updateDate: "1231",
    children: [],
  },
  {
    id: "3",
    departmentHierarchy: "1.2",
    departmentName: "third",
    _links: {},
    administratorId: "12312",
    creationDate: "12312",
    historyId: "12312",
    isActive: true,
    isDeleted: false,
    isOwner: { UPDATE: false, DELETE: false },
    updateDate: "1231",
    children: [],
  },
  {
    id: "2",
    departmentHierarchy: "1",
    departmentName: "second",
    _links: {},
    administratorId: "12312",
    creationDate: "12312",
    historyId: "12312",
    isActive: true,
    isDeleted: false,
    isOwner: { UPDATE: false, DELETE: false },
    updateDate: "1231",
    children: [],
  },
];

test("getDepartmentHierarchy", () => {
  expect(getDepartmentHierarchy("3", departments)).toEqual([
    {
      id: "1",
      departmentHierarchy: "",
      departmentName: "first",
      _links: {},
      administratorId: "12312",
      creationDate: "12312",
      historyId: "12312",
      isActive: true,
      isDeleted: false,
      isOwner: { UPDATE: false, DELETE: false },
      updateDate: "1231",
      children: [],
    },
    {
      id: "2",
      departmentHierarchy: "1",
      departmentName: "second",
      _links: {},
      administratorId: "12312",
      creationDate: "12312",
      historyId: "12312",
      isActive: true,
      isDeleted: false,
      isOwner: { UPDATE: false, DELETE: false },
      updateDate: "1231",
      children: [],
    },
    {
      id: "3",
      departmentHierarchy: "1.2",
      departmentName: "third",
      _links: {},
      administratorId: "12312",
      creationDate: "12312",
      historyId: "12312",
      isActive: true,
      isDeleted: false,
      isOwner: { UPDATE: false, DELETE: false },
      updateDate: "1231",
      children: [],
    },
  ]);
});
