const HTTP_CODES = {
  SUCCESS: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};

const ERROR_SCREEN_CODES = [
  HTTP_CODES.BAD_REQUEST,
  HTTP_CODES.UNAUTHORIZED,
  HTTP_CODES.FORBIDDEN,
  HTTP_CODES.SERVER_ERROR,
];

const AUTH_COOKIE_SESSION = "JSESSIONID";
const AUTH_COOKIE_USERNAME = "username";
const AUTH_COOKIE_REMEMBER_ME = "rememberMe";

module.exports = {
  ERROR_SCREEN_CODES,
  HTTP_CODES,
  AUTH_COOKIE_SESSION,
  AUTH_COOKIE_USERNAME,
  AUTH_COOKIE_REMEMBER_ME,
};
